### PR TITLE
Update to VS2017 and released .net core

### PR DESCRIPTION
**Pull request by dontjee**

### CODE REVIEW

**Comment by jkling** [comment]
Looks good to me. My main concern would be understanding if this is forward compatible or not. A lot of projects still exist on older versions of .NET, so it'd be nice to know if this will force them to upgrade or not. As long as we're releasing a major revision, though, I don't particularly care.

**Comment by dontjee** [comment]
> As long as we're releasing a major revision, though, I don't particularly care.

Definitely planning to major rev this. I planned to release it as 9.0.0-alpha002, replacing the old alpha we had out there. If it checks out I think we call this the official 9.0.0 release.

**Comment by dontjee** [comment]
> A lot of projects still exist on older versions of .NET, so it'd be nice to know if this will force them to upgrade or not

Worth noting that .net 4.5 is technically deprecated - https://blogs.msdn.microsoft.com/dotnet/2015/12/09/support-ending-for-the-net-framework-4-4-5-and-4-5-1/

**Comment by jkling** [comment]
> Worth noting that .net 4.5 is technically deprecated - https://blogs.msdn.microsoft.com/dotnet/2015/12/09/support-ending-for-the-net-framework-4-4-5-and-4-5-1/

Cool to see Microsoft being a little faster about deprecating things. AFAIK 4.6.2+ is still supported, so I'm still curious how this interacts with those. But overall I have nothing against just moving forward to .NET Core.

**Comment by dontjee** [comment]
> AFAIK 4.6.2+ is still supported, so I'm still curious how this interacts with those

Added two more commits. 

In e53a02b I switched to targeting netstandard 1.5 which means we can install this on .net 4.6.2 projects. Once netstandard 2.0 is out we should switch to that because it targets .net core and .net 4.6.1 and up but I think this is the best we can do for now.

**Comment by jkling** [comment]
> Added two more commits.
> 
> In e53a02b I switched to targeting netstandard 1.5 which means we can install this on .net 4.6.2 projects. Once netstandard 2.0 is out we should switch to that because it targets .net core and .net 4.6.1 and up but I think this is the best we can do for now.

Good stuff. Thanks for taking a look into the compatibility stuff. :shipit:

**Pull request merged**
