### PR TITLE
Fix bug where existing memory context instances lost access to static state after Reset was called

### PR DESCRIPTION
**Pull request by dontjee**

### CODE REVIEW

**Comment by jefflward** [comment]
:+1:

**Comment by dontjee** [comment]
> Does this require a documentation update?

This is only a bug fix, not really a new feature so I wasn't going to. What docs were you thinking?

**Comment by dontjee** [comment]
> It'd be nice we could start adding XML Comments to the public methods in Hyde (like the method you added  ). I find it frustrating to work with because I get zero intellisense. Otherewise,

I don't think they apply in this case since I added an internal method but yeah we could use some on the interfaces at least. Hyde is also open source and we're accepting contributions if you're interested :stuck_out_tongue:

**Comment by StilgarISCA** [comment]
Sorry the clear method isn't publically exposed, so carry on.

**Pull request merged**
